import React from "react";
import './AsciiLogo.css'

const AsciiLogo = (props) => {

    return (
        <div className='asciilogo'>
        <pre>
            {`MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWWXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMW0dc;'...................................................................................................................................................................';cdONMMMMMMMMMMMMM
MMMMMMMMMMMKl..    ...................................................................................................................................................................  ..;kNMMMMMMMMMMM
MMMMMMMMMMXl.   .:dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl,.  .kMMMMMMMMMMM
MMMMMMMMMM0,   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:. .xWMMMMMMMMMM
MMMMMMMMMMX:.  'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl. ;0MMMMMMMMMMM
MMMMMMMMMMWk'  .cXMMMMMMMMMMMMMMMMMMWK0XWMMMMWKO0NMMMMMWXOxdold0NMMMMMMMWKkONMMMMW0kxONMMMMMN0kxxxOKNWMMMMMN0kxxxxxxdxxOXMMMMMMMMMMMMMW0dc;;;cx0NMMMMMMMMNOxxxdolllloxKWMMMMMMMMMMMMMMWk' .xWMMMMMMMMMMM
MMMMMMMMMMMNo.  .dNMMMMMMMMMMMMMMMMNd..;KMMMMk' .dWMMW0c..     .;xXMMMMWk. .dWMMMK;  .OMMMNx,. ..  .,lKMMMWx.   .......'xWMMMMMMMMMMWO:.   ..  .;OWMMMMMNl.           cNMMMMMMMMMMMMMMK; .cXMMMMMMMMMMMM
MMMMMMMMMMMMXc.  'kWMMMMMMMMMMMMMMMNc  '0MMMMk.  oWMM0,  .;ldo;.  lNMMMMx.  lNMMM0'  .xMMM0'  ,kKx,..'kWMMWd.  :OKKKK00KNMMMMMMMMMMM0,  .:OKKd'  ,KMMMMMNc   .clllllloOWMMMMMMMMMMMMMXl. ,OMMMMMMMMMMMMM
MMMMMMMMMMMMM0;   ;0MMMMMMMMMMMMMMMWo  '0MMMMk.  oWMWd. .xWMMMNl  .kMMMMk.  cNMMM0'  .OMMMK;  .lKWNK0KNMMMWo   lNMMMMMMMMMMMMMMMMMMWd.  cNMMMMO.  oWMMMMNc  .dWMMMMMMMMMMMMMMMMMMMMMWx. .dWMMMMMMMMMMMMM
MMMMMMMMMMMMMWk'  .cXMMMMMMMMMMMMMMMx. ,KMMMMO.  oWMNc  '0MMMMMx. .dWMMMk.  cNMMMK;  .OMMMW0c.  .l0WMMMMMMWo   .:lllloxXMMMMMMMMMMMWo  .dWMMMMK,  ;XMMMMNl  .xMMMMMMMMMMMMMMMMMMMMMMO, .:XMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWd.  .dWMMMMMMMMMMMMMMx. .xKK0Oo.  oWMK;  .OMMMMMk.  lNMMMk.  oWMMMX;  .OMMMMMWKo'  .cdONMMMWo    .'''..cKMMMMMMMMMMMWd. .xMMMMMK;  ,KMMMMMd.  ,xO000XWMMMMMMMMMMMMMMXc. 'OWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXc.  'OWMMMMMMMMMMMMWd.  ....     oWMK,  .kMMMMMx.  oWMMMk.  oWMMMX;  .kMMMMMMMWKd'   .oNMMWd.  :KNNNXXNMMMMMMMMMMMMMd. .xMMMMMX;  ;KMMMMWd       ..'kWMMMMMMMMMMMMNo. .dWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM0,  .:KMMMMMMMMMMMMWo   ..,;;'   oWMK,  .OMMMMWo  .dWMMMk.  lWMMMK;  .xMMMXkdONMW0,   ,KMMWd.  lNMMMMMMMMMMMMMMMMMMMx.  dWMMMMNc  ,KMMMMWo    .,,'',kWMMMMMMMMMMMWk. .cXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWx.  .lXMMMMMMMMMMMNc  .xXNWWO' .dWMX;  .OMMMMX;  .kMMMMO.  ,ONWXd.  'OMMMO' .:dxc.   cXMMMx.  .dOO000KKXWMMMMMMMMMMK,  ;OWMMMX;  ;KMMMMWd.  cXNWNNNWMMMMMMMMMMMMK;. ,OMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNo.  .dWMMMMMMMMMMNl  ,0MMMMO.  oWMNl   cKNX0c.  ;KMMMMX:   .,;.  .,OWMMMWO;.    .';lKMMMMk.    .......'xWMMMMMMMMMWO,  .:dkk:.  cNMMMMWd.  oWMMMMMMMMMMMMMMMMMNl. .dWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXc.  'OMMMMMMMMMMWl  '0MMMMk.  oWMM0,   .''.  .lXMMMMMMXxc;,,;:cdONMMMMMMMWKOxxk0NWWMMMMMW0kddxxxxddddxKWMMMMMMMMMMMXo'.       'kWMMMMWo   oWMMMMMMMMMMMMMMMMWx. .cXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMM0,  .:XMMMMMMMMMNl  .OMMMMk.  oWMMWKc.. ...;o0WMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:::cdKWMMMMMWd.  oWMMMMMMMMMMMMMMMMO,  ,OMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWx.  .oNMMMMMMMMNc  .kMMMMk. .dWMMMMWX000KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMk. .xWMMMMMMMMMMMMMMMK:. .xWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNl.  .xWMMMMMMMX:  .kMMMMKddONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKO0NMMMMMMMMMMMMMMMNo. .lNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMK:.  ,0MMMMMMMNx:cxNMMMMMMMMMXkxdOWMMMMMMMMMMW0xddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddONNklccccccccccccdKMMMMMMMMMMMMMMMMMMMMMO'  ,0MMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWO,  .cXMMMMMMMMWMMMMMMMMMMMMO'  ;KMMMMMMMMMNx.  .....................................................         .cN0'             ;KMMMMMMMMMMMMMMMMMMMMK:. .xWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWx.  .dNMMMMMMMMMMMMMMMMMMMMX:  .kMMMMMMMMNo. .d0KKKK0KKKKK0000000000000000000000000000000000000000OOOkkkkOkkkOXXl  ,dkxxxkxxkxkKWMMMMMMMMMMMMMMMMMMMNl. .lNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNl.  'kWMMMMMMMMMMMMMMMMMMMWx.  cNMMMMMMXc  .kWMMMNxcccdXMMMMMMMMNxllkNMMMMMMMMMNxo0WMMMW0olooooooodddddddddx0WO. .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx. .:KMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMK:.  ;0MMMMMMMMMMMMMMMMMMMMK;  '0MMMMWK:  'kWMMMXl... .kMMMMMMMMk.  .lXMMMMMMMWx..xWMMMK;  ;ooooooooodd:.  .xXc  cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,  'kMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWO,  .cXMMMMMMMMMMMMMMMMMMMWd. .dWMMWO,  ,0WMMMNl .xx..dWMMMMMMX; ..  ;0WMMMMMK; ;KMMMWx. '0MMMMMMMMMMNl   ;K0' ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc. .oNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWx.  .dWMMMMMMMMMMMMMMMMMMM0'  :XMWk'  ;0MMMMNl..xW0' cNMMMMMWd..xO;  .xNMMMWd..dWMMMK;  ;kOO00000KKKx.  .dXl  :O000000000KWMMMMMMMMMMMMMMMMMMMWd. .:KMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNl.  'kWMMMMMMMMMMMMMMMMMMNl  '0Nd.  :KMMMMXl.'OWMK; ,KMMMMM0, cXMXo. .lXMMK; ,KMMMWk'...............   ;Kx.  ...........lXMMMMMMMMMMMMMMMMMMWk'  ,OWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMK;.  ;0MMMMMMMMMMMMMMMMMMMk. .cc  .lXMMMMXc  ,oool. .kMMMMWo .OMMMWO,  ,kXd..dWMMMMNK0000000OOOOOOl.  .k0, .lkkkkkkkkkkONMMMMMMMMMMMMMMMMMMMK;  .xWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWO'  .cXMMMMMMMMMMMMMMMMMMX;     .oNMMMMXc..:cclll:. oWMMM0' lNMMMMMKc. ... ,KMMMMKxdxXMMMMMMMMMMNl   :Kl  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl. .lNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .dWMMMMMMMMMMMMMMMMMWd.   .dNMMMMXl.'OWMMMMM0, :XMMNl ,0MMMMMMMNx.   .dWMMMXc  .okxxkkkkkkko.  .kO'  ,dxxxxxxxxxx0WMMMMMMMMMMMMMMMMMWx.  ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.  'OWMMMMMMMMMMMMMMMMMXdlllkWMMMMMKlcOWMMMMMMNd:dNMMXc,kWMMMMMMMMW0:..:KMMMMK:''',,,,,,,,,,,,'''oXx,''.'''''''''.,kWMMMMMMMMMMMMMMMMM0,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  .:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWNNWMMMMMMMMMMMWXXNMMMMMWNNNNNNNNNNNNNNNNNNNWMWNNNXXNXXXXXXXXNWMMMMMMMMMMMMMMMMMXc. .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'  .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. .:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKKKKXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.  'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxoc,'...........',;cldONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  .:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0x0K0Ox0KOKKxkNMMMNo.                     .:0MMMW0KKxOOk0kONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dk00kdk0k00xkNMMMMXkdl;,'',,,'',,,,;:;,,'lKWMMMW0KKxkkx0xkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMWMMWWMWWMMMMMMMMNd::oKXXXXXXXNNWXd::kWMMMMMMMMWMMWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0KNWMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc. .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  .:KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. .;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .,d0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:. .;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.  ..,clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc:'. .'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc,..                                                                                                               ..;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kxolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`}        
    
        </pre>
        </div>
    );
};

export default AsciiLogo;